var logModule = require("./modules/Object")
var test = require("./modules/function")
var message= require("./modules/string")
var array = require("./modules/array")
// logModule.info('This info coming from server.js')
// logModule.warn('This warning coming from server.js')
// logModule.error('This error coming from server.js')
console.log(logModule)
console.log(test())
console.log(message)
console.log(array)